apiVersion: 1
groups:
  - orgId: 1
    name: telco_churn_alerts
    folder: epamemo
    interval: 1m
    rules:
      # 1) Model endpoint mati
      - uid: alert_model_down
        title: Model Down
        condition: C
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Model endpoint down (app_model_up < 1)"
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              refId: A
              expr: app_model_up
              instant: true
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              refId: C
              type: threshold
              expression: A
              conditions:
                - evaluator:
                    type: lt
                    params: [1]

      # 2) Ada error inferensi
      - uid: alert_prediction_errors
        title: High Prediction Error Rate
        condition: C
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Terjadi error prediksi (rate > 0)"
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              refId: A
              expr: sum(rate(app_prediction_errors_total[5m]))
              instant: true
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              refId: C
              type: threshold
              expression: A
              conditions:
                - evaluator:
                    type: gt
                    params: [0]

      # 3) Latensi request tinggi
      - uid: alert_high_latency
        title: High Request Latency
        condition: C
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Latensi p95 request > 1 detik"
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              refId: A
              expr: histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket[5m])) by (le))
              instant: true
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              refId: C
              type: threshold
              expression: A
              conditions:
                - evaluator:
                    type: gt
                    params: [1]
